version: '3.3'

services:
  postgres:
    image: "postgres:9"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: supersecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata

  rocket:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    links:
      - postgres
    # diesel infer_schema macro gives warnings with this flag.
    # environment:
    #   - CARGO_INCREMENTAL=1
    command: cargo watch -x run

volumes:
  pgdata: {}
